name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set version ${{ github.event.release.tag_name }}
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
      - name: Publish package
        run: mvn -P release --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

  updateReadme:
    runs-on: ubuntu-latest
    needs: [ publish ]
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update for Maven
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md
          prefix: "<version>"

      - name: Update for Gradle
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md
          prefix: "se.bufferoverflow:sieport:"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README with latest release version
          title: Update README with latest release version
          delete-branch: true
          base: main