name: Update documentation on release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update for Maven
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md
          prefix: "<version>"

      - name: Update for Gradle
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md
          prefix: "se.bufferoverflow:sieport:"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README with latest release version
          title: Update README with latest release version
          delete-branch: update-readme
          base: main
